import React from 'react';
import { StudyContent } from '../types';

interface ResultViewProps {
  data: StudyContent;
  topic: string;
  onReset: () => void;
}

export const ResultView: React.FC<ResultViewProps> = ({ data, topic, onReset }) => {
  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-700 w-full max-w-4xl mx-auto space-y-6 pb-20">
      
      {/* Header with Topic Title */}
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-3xl font-bold text-slate-900 tracking-tight">{topic}</h2>
          <p className="text-slate-500 mt-1">Explanation generated by ScholarSync AI</p>
        </div>
        <button 
          onClick={onReset}
          className="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 hover:text-brand-600 transition-colors"
        >
          New Topic
        </button>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* Definition Card - Spans full width on mobile, half on desktop */}
        <div className="md:col-span-2 glass-panel p-8 rounded-3xl shadow-sm border border-slate-200/60 bg-white/80">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-blue-100 rounded-lg text-blue-600">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
            </div>
            <h3 className="text-xl font-bold text-slate-800">Definition</h3>
          </div>
          <p className="text-lg leading-relaxed text-slate-700 font-medium">
            {data.definition}
          </p>
        </div>

        {/* Key Points Card */}
        <div className="glass-panel p-6 rounded-3xl shadow-sm border border-slate-200/60 bg-white/80">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-amber-100 rounded-lg text-amber-600">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20"/><path d="m17 5-5-3-5 3"/><path d="m17 19-5 3-5-3"/></svg>
            </div>
            <h3 className="text-xl font-bold text-slate-800">Key Points</h3>
          </div>
          <ul className="space-y-3">
            {data.keyPoints.map((point, index) => (
              <li key={index} className="flex gap-3 text-slate-600 items-start">
                <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-500 mt-0.5">
                  {index + 1}
                </span>
                <span className="leading-relaxed">{point}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Example Card */}
        <div className="glass-panel p-6 rounded-3xl shadow-sm border border-slate-200/60 bg-gradient-to-br from-white to-emerald-50/50">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-emerald-100 rounded-lg text-emerald-600">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg>
            </div>
            <h3 className="text-xl font-bold text-slate-800">Example</h3>
          </div>
          <div className="bg-white/60 p-4 rounded-xl border border-emerald-100/50">
            <h4 className="font-semibold text-emerald-900 mb-2">{data.example.title}</h4>
            <p className="text-slate-600 italic leading-relaxed">
              "{data.example.content}"
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
